Stripe Payouts
staynomad/Nomad-Front pull request #468
Opened 2021-06-18 22:14 UTC by nishantbalaji

2021-06-18 22:18 UTC, nishantbalaji commented
Test this concurrently with the PR in the Backend directory

2021-06-18 23:17 UTC, nishantbalaji commented
Changes

- connect button on profile
- dashboard link on profile

2021-06-19 19:34 UTC, aidenszeto reviewed
I feel like the Payouts tab is a bit empty (only has one button on it) so we should experiment with adding more information to the page, ie. instructions on how to set up the Stripe connection. We should also play around with including it in the Settings tab which is currently empty.

Let's discuss this some more at the next meeting make a decision from there.

2021-06-19 19:36 UTC, aidenszeto reviewed
@nishantbalaji LGTM. Before we merge, could you add a comment on how to test/verify functionality? Not sure how Stripe manages testing transactions but we should make sure everything works in the testing environment first.

2021-06-19 19:57 UTC, aidenszeto requested changes

2021-06-19 19:57 UTC, aidenszeto commented on src/components/myAccount/payout.component.js
> +import { useSelector, useDispatch } from "react-redux";
Doesn't look like we're using `useDispatch` here - should remove from import

2021-06-19 20:12 UTC, nishantbalaji commented
> I feel like the Payouts tab is a bit empty (only has one button on it) so we should experiment with adding more information to the page, ie. instructions on how to set up the Stripe connection. We should also play around with including it in the Settings tab which is currently empty.
> 
> Let's discuss this some more at the next meeting make a decision from there.

Yeah I agree its a bit empty, but I didn't know where else to specifically put it. I also thought the stripe dashboard would be an integrated view but since its in a separate page we could just drop it in one of the other pages.

2021-06-19 20:14 UTC, nishantbalaji commented
> @nishantbalaji LGTM. Before we merge, could you add a comment on how to test/verify functionality? Not sure how Stripe manages testing transactions but we should make sure everything works in the testing environment first.

To test with the testing environment, the keys have to be the testing keys. I think only the prod environment uses the live keys so anything we do with the testing keys will use the testing environment.

2021-06-19 20:34 UTC, aidenszeto commented
I see. For the testing keys will you still need a valid account to connect with Stripe then?

Also how will Stripe know how much to pay out the hosts btw? Is that something we pass in?

2021-06-22 01:28 UTC, aidenszeto approved these changes

2021-06-22 22:02 UTC, aidenszeto approved these changes

2021-06-22 22:06 UTC, merged