Stripe button
staynomad/Nomad-Front pull request #489
Opened 2021-07-15 20:17 UTC by syd-tan

# Moved Stripe Button

Closes #487 #469 

# Summary of change

- Removed payouts tab under account page since it only contained the Stripe button
- Stripe button moved under profile above edit profile button
- Styled dashboard button that appears once user has connected to stripe 

Should look like this under profile tab
Before connecting with stripe 
<img width="472" alt="Screen Shot 2021-07-15 at 1 12 51 PM" src="https://user-images.githubusercontent.com/65259944/125851604-ea57c96b-0a8b-4da3-9505-4307281c264c.png">

After connecting with stripe
<img width="475" alt="Screen Shot 2021-07-15 at 1 13 30 PM" src="https://user-images.githubusercontent.com/65259944/125851676-27b6000a-7574-4082-9477-29487677e302.png">

# Testing/Verification

- Checked a profile that has been connected to stripe and one that hasn't

2021-07-15 20:59 UTC, nishantbalaji approved these changes

2021-07-15 20:59 UTC, nishantbalaji commented on src/components/myAccount/payout.css
> +
This was a bit lazy by me but it works so

2021-07-15 23:47 UTC, aidenszeto requested changes
LGTM, just one small fix -

![image](https://user-images.githubusercontent.com/66970460/125871463-81e4bc82-ffc5-4be2-939c-638ee250cc71.png)

Doesn't look like Payout is being called directly in the menu component any more so we can remove the import on line 10 of `menu.component.js`

2021-07-16 01:03 UTC, nishantbalaji commented
> LGTM, just one small fix -
> 
> ![image](https://user-images.githubusercontent.com/66970460/125871463-81e4bc82-ffc5-4be2-939c-638ee250cc71.png)
> 
> Doesn't look like Payout is being called directly in the menu component any more so we can remove the import on line 10 of `menu.component.js`

@aidenszeto Fixed in last commit

2021-07-16 04:40 UTC, aidenszeto approved these changes

2021-07-16 04:45 UTC, merged