UTC Time Change Fixes
staynomad/Nomad-Front pull request #492
Opened 2021-07-21 01:38 UTC by lullofthesea

Closes #376

Updated sorting / reservation buttons / times to match new UTC Timestamp format in database.

Tested only with 1 listing -> buttons working fine / times stored and displayed properly.

2021-07-21 18:39 UTC, aidenszeto approved these changes

2021-07-21 18:41 UTC, aidenszeto requested changes

2021-07-21 18:41 UTC, aidenszeto commented on src/components/createListing/createListing.component.js
> +      coordinates: this.state.form.coordinates,
I believe we call this `coords` instead of `coordinates` actually

2021-07-21 18:43 UTC, aidenszeto approved these changes

2021-07-22 21:19 UTC, nishantbalaji approved these changes
LGTM, could you update the precommit hook on this PR so we dont do `git add .` everytime? I updated it for the backend with the email-styling PR

2021-07-27 01:07 UTC, merged